services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: moores_law_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  web_service:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://ml_user:securepassword@mongodb:27017/moores_law_db?authSource=moores_law_db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5050" ]
      interval: 10s
      timeout: 5s
      retries: 5
